version: "3"
name: full-cycle-nginx-node
services:
  mysqldb:
    container_name: mysqldb
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - full-cycle-network

  node-server:
    container_name: node-server
    build: ./node
    ports:
      - 8080:8080
    networks:
      - full-cycle-network
    volumes:
      - ./node/volume:/volume
    depends_on:
      - mysqldb
    tty: true
    entrypoint: dockerize -wait tcp://mysqldb:3306 -timeout 50s node src/main.js

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    networks:
      - full-cycle-network
    depends_on:
      - node-server

networks:
  full-cycle-network:
    driver: bridge
